version: '3.7'

services:
  featurehub-app:
    build:
      context: .
      dockerfile: FeatureHub.Console/Dockerfile
    environment:
      HUB_URL: "http://host.docker.internal:8085"
      HUB_API_KEY: ""
      CONN: "Host=hub-database;Port=5432;Database=postgres;User Id=postgres;Password=postgres;"
    depends_on:
      - hub
      - hub-database
    networks:
      - hub-network

  feature-api:
    build:
      context: .
      dockerfile: FeatureHub.Api/Dockerfile
    environment:
      CONN: "Host=hub-database;Port=5432;Database=postgres;User Id=postgres;Password=postgres;"
    ports:
      - 8080:80
    depends_on:
      - hub-database
    networks:
      - hub-network

  hub:
    image: featurehub/party-server:latest
    ports:
      - 8085:8085
    volumes:
      - hubdb:/db
    networks:
      - hub-network

  hub-database:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Prv
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hub-network

networks:
  hub-network:

volumes:
  hubdb:
  pgdata: