version: '3.7'

services:
  featurehub-app:
    image: ${DOCKER_REGISTRY-}featurehub-app
    build:
      context: .
      dockerfile: FeatureHub.Console/Dockerfile
    networks:
      - hub-network

  feature-api:
    image: ${DOCKER_REGISTRY-}feature-api
    build:
      context: .
      dockerfile: FeatureHub.Api/Dockerfile
    networks:
      - hub-network

networks:
  hub-network: